# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Last updated: 20230623:22:32

name: Builds and push the image  of vms_domain_application to docker.io app - AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'aws-self-hosted'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ${{vars.ACR_DOKCERHUB}}
        username: ${{secrets.ACRUSERNAME_DOKCERHUB}}
        password: ${{secrets.ACRUSERPASSWORD_DOKCERHUB}}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{vars.ACR_DOKCERHUB}}/${{secrets.ACRUSERNAME_DOKCERHUB}}/vms_users:main
        file: ./Dockerfile
